consul1:
  image: "fatlazycat/consul:latest"
  container_name: "consul1"
  hostname: "consul1"
  ports:
    - "8080:8080"
  command: "agent -data-dir /data -server -bootstrap-expect 3 -ui-dir /ui -client=0.0.0.0"

consul2:
  image: "fatlazycat/consul:latest"
  container_name: "consul2"
  hostname: "consul2"
  ports:
    - "8080"
  links:
    - "consul1:consul1"
    - "consul3:consul3"
  command: "agent -server -join consul1"

consul3:
  image: "fatlazycat/consul:latest"
  container_name: "consul3"
  hostname: "consul3"
  ports:
    - "8080"
  links:
    - "consul1:consul1"
    - "consul2:consul2"
  command: "agent -server -join consul1"
