version: '2'

services:
  etcd1:
    image: "quay.io/coreos/etcd:latest"
    container_name: "etcd1"
    hostname: "etcd1"
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    volumes:
      - ~/Development/Environment/Etcd/data/n1:/data
      - ~/Development/Environment/Etcd/cfssl:/etc/ssl/certs
    command:
      - --name=etcd1
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=etcd1=http://etcd1.docker:2380,etcd2=http://etcd2.docker:2480,etcd3=http://etcd3.docker:2580
      - --initial-cluster-state=new
      - --initial-advertise-peer-urls=http://etcd1.docker:2380
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd1.docker:2379
      - --data-dir=/data
      - --debug

  etcd2:
    image: "quay.io/coreos/etcd:latest"
    container_name: "etcd2"
    hostname: "etcd2"
    ports:
      - "2479:2379"
      - "2480:2380"
      - "4401:4001"
    volumes:
      - ~/Development/Environment/Etcd/data/n2:/data
      - ~/Development/Environment/Etcd/cfssl:/etc/ssl/certs
    command:
      - --name=etcd2
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=etcd1=http://etcd1.docker:2380,etcd2=http://etcd2.docker:2480,etcd3=http://etcd3.docker:2580
      - --initial-cluster-state=new
      - --initial-advertise-peer-urls=http://etcd2.docker:2480
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd2.docker:2479
      - --data-dir=/data

  etcd3:
    image: "quay.io/coreos/etcd:latest"
    container_name: "etcd3"
    hostname: "etcd3"
    ports:
      - "2579:2379"
      - "2580:2380"
      - "4501:4001"
    volumes:
      - ~/Development/Environment/Etcd/data/n3:/data
      - ~/Development/Environment/Etcd/cfssl:/etc/ssl/certs
    command:
      - --name=etcd3
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=etcd1=http://etcd1.docker:2380,etcd2=http://etcd2.docker:2480,etcd3=http://etcd3.docker:2580
      - --initial-cluster-state=new
      - --initial-advertise-peer-urls=http://etcd3.docker:2580
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd3.docker:2579
      - --data-dir=/data
