version: '2'

services:
  etcd0:
    image: "quay.io/coreos/etcd:latest"
    container_name: "etcd0"
    hostname: "etcd0"
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    volumes:
      - ~/Development/Environment/Consul/ssl:/etc/ssl/certs
    command:
      - --name=etcd0
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - --initial-cluster-state=new
      - --initial-advertise-peer-urls=http://etcd0:2380
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd0:2379
      - --client-cert-auth=true
      - --cert-file=/etc/ssl/certs/consul.cert
      - --key-file=/etc/ssl/certs/consul.key
      - --trusted-ca-file=/etc/ssl/certs/ca.cert
      - --peer-client-cert-auth=true
      - --peer-cert-file=/etc/ssl/certs/consul.cert
      - --peer-key-file=/etc/ssl/certs/consul.key
      - --peer-trusted-ca-file=/etc/ssl/certs/ca.cert

  etcd1:
    image: "quay.io/coreos/etcd:latest"
    container_name: "etcd1"
    hostname: "etcd1"
    ports:
      - 2379
      - 2380
      - 4001
    volumes:
      - ~/Development/Environment/Consul/ssl:/etc/ssl/certs
    command:
      - --name=etcd1
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - --initial-cluster-state=new
      - --initial-advertise-peer-urls=http://etcd1:2380
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd1:2379
      - --client-cert-auth=true
      - --cert-file=/etc/ssl/certs/consul.cert
      - --key-file=/etc/ssl/certs/consul.key
      - --trusted-ca-file=/etc/ssl/certs/ca.cert
      - --peer-client-cert-auth=true
      - --peer-cert-file=/etc/ssl/certs/consul.cert
      - --peer-key-file=/etc/ssl/certs/consul.key
      - --peer-trusted-ca-file=/etc/ssl/certs/ca.cert

  etcd2:
    image: "quay.io/coreos/etcd:latest"
    container_name: "etcd2"
    hostname: "etcd2"
    ports:
      - 2379
      - 2380
      - 4001
    volumes:
      - ~/Development/Environment/Consul/ssl:/etc/ssl/certs
    command:
      - --name=etcd2
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - --initial-cluster-state=new
      - --initial-advertise-peer-urls=http://etcd2:2380
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd2:2379
      - --client-cert-auth=true
      - --cert-file=/etc/ssl/certs/consul.cert
      - --key-file=/etc/ssl/certs/consul.key
      - --trusted-ca-file=/etc/ssl/certs/ca.cert
      - --peer-client-cert-auth=true
      - --peer-cert-file=/etc/ssl/certs/consul.cert
      - --peer-key-file=/etc/ssl/certs/consul.key
      - --peer-trusted-ca-file=/etc/ssl/certs/ca.cert
